"""Add sort_order to Capabilities

Revision ID: 68e4d315c023
Revises: 
Create Date: 2025-07-22 16:23:08.376250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68e4d315c023'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carousel')
    op.drop_table('about_us')
    with op.batch_alter_table('capabilities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('why_rangaatma', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('why_rangaatma', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('capabilities', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('sort_order')

    op.create_table('about_us',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('img', sa.VARCHAR(length=255), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carousel',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('img', sa.VARCHAR(length=255), nullable=True),
    sa.Column('title', sa.VARCHAR(length=100), nullable=True),
    sa.Column('subtitle', sa.VARCHAR(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
