"""Added is_read to CustomerQuery

Revision ID: 77b9b6574c17
Revises: 68e4d315c023
Create Date: 2025-07-25 17:18:07.098827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77b9b6574c17'
down_revision = '68e4d315c023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_query', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_query', schema=None) as batch_op:
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###
